set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_flamingo}] #{pane_current_command} '

run ~/.config/tmux/themes/catppuccin/catppuccin.tmux
